#! /usr/bin/env python
"""
PyLEMS command line startup script.

@author: Gautham Ganapathy
@organization: LEMS (http://neuroml.org/lems/, https://github.com/organizations/LEMS)
@contact: gautham@lisphacker.org
"""

from lems.run import main

if __name__ == '__main__':
    main()
