# Check that examples are same in pylems and in jlems
name: Check LEMS examples

on:
  push:
    branches:  [ master, development, experimental ]

jobs:
  verify:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: nelonoel/branch-name@v1.0.1

    # https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Checkout jlems
      uses: actions/checkout@v3
      with:
        repository: LEMS/jLEMS
        ref: ${{ steps.extract_branch.outputs.branch }}
        path: jlems

    - name: check examples
      run: |
        for ex in "example1.xml" "example2.xml" "example3.xml" "example4.xml" "example5.xml" "example6.xml" "example7.xml" "example8.xml" "bounce-conditional.xml" ; do

          if ! diff -ur "examples/$ex" "jlems/src/test/resources/$ex" ; then
            echo "Example file $ex is not identical"
            exit -1
          fi
        done
